main:

  - title: CNN-based Animal Recognition System
    year: 2024
    attribute: YGP Preparatory AI Course Project
    description: Responsible for dataset downloading, preprocessing, and final reporting. The innovation lies in training the CNN from scratch without freezing earlier layers, along with introducing improvements in pooling strategies and cosine annealing scheduling to enhance convergence and accuracy.
    tech_stack: Python, PyTorch, OpenCV
    outcome: Course project submitted with full pipeline documentation and performance analysis.
    image: ./assets/img/project_animal_recognition.png

  - title: U-Transformer Architecture for Meteorological Prediction
    year: 2024
    attribute: YGP Preparatory AI Course Project
    description: Contributed to partial code development for a weather forecasting model based on a U-Transformer structure. The design integrates strengths from both Pangu and Fuxi large weather models, implemented using the domestic PaddlePaddle deep learning framework to support efficient spatial-temporal prediction.
    tech_stack: Python, PaddlePaddle, NumPy
    outcome: Functional prototype for multi-step meteorological variable forecasting.
    image: ./assets/img/project_weather_prediction.png

  - title: Cross-Platform PPT Remote Control Tool
    year: 2025
    attribute: Open Source Project
    description: Designed and implemented a lightweight remote control solution based on web and local bridge programs. Utilized Firebase for real-time signaling synchronization and employed a local Node.js script to parse commands and simulate keyboard events, enabling seamless control of PC-side PPT presentations from a mobile device.
    tech_stack: JavaScript, Node.js, Firebase Realtime Database
    link: https://github.com/lsqkk/ppt-remote
    image: ./assets/img/project_ppt_remote.png

  - title: Serverless P2P File Transfer System
    year: 2025
    attribute: Personal Blog Service
    description: To overcome the limitation of lacking a dedicated signaling server, I established a signaling channel using Firebase Realtime Database. Combined with WebRTC technology and public STUN servers, this system enabled direct peer-to-peer file transfer between browsers.
    tech_stack: JavaScript (WebRTC API), Firebase
    link: https://lsqkk.github.io/a/share
    image: ./assets/img/project_p2p_file.png

  - title: AI-Based Forest Fire Prediction Model
    year: 2025
    attribute: AIC Competition Project
    description: Responsible for the multimodal data preprocessing pipeline, specifically handling the download, cleaning, and spatial interpolation of ERA5 reanalysis meteorological data to provide structured input for subsequent CNN and large language model training, and made innovations based on the YingLong Model.
    tech_stack: Python, PaddlePaddle
    outcome: The project won a provincial third prize in the AIC competition.
    image: ./assets/img/project_forest_fire.png

  - title: Personal Server Deployment and Operation
    year: 2025
    description: Deployed and maintained a home server cluster on Orange Pi, stably running various services including Ollama (local large language model service), Nextcloud (private cloud storage), WordPress (website management), etc. Gained practical experience in Linux system administration, containerized application deployment, and intranet penetration techniques.
    tech_stack: Linux, Docker, Orange Pi
    image: ./assets/img/project_orange_pi.png

  - title: Personal Independent Blog Development
    year: 2025
    description: Designed, developed from scratch, and continuously maintain a static blog system for sharing technical notes and project summaries. The system achieves zero server backend deployment, with all code open-sourced. The site has obtained a software copyright.
    tech_stack: JavaScript, HTML/CSS, Jekyll
    link: https://lsqkk.github.io/
    image: ./assets/img/project_blog.png